# This is a basic workflow that is manually triggered

name: Manual workflow
on:
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
            -Dsonar.organization=amitpuri-github
            -Dsonar.projectKey=amitpuri-Shabdkosh
            -Dsonar.cs.xunit.reportsPaths=CodeCoverageResults/3f231c14-8866-4e21-8db4-92f8ddb496b1/coverage.opencover.xml	
            -Dsonar.coverage.exclusions=coveragereport/**
            -Dsonar.verbose=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
