# This is a basic workflow that is manually triggered

name: Manual workflow
on:
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args:
            -Dsonar.organization=Amit Puri
            -Dsonar.projectKey=amitpuri-github
            -Dsonar.cs.xunit.reportsPaths=CodeCoverageResults/b8487403-385e-4238-89b4-d623e290a808/coverage.cobertura.xml	
            -Dsonar.verbose=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
